# Generated by Django 5.0.1 on 2024-02-04 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0002_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='football_app.match'),
        ),
    ]
